export const categories = [
  { id: 'pizza', label: 'Pizzas' },
  { id: 'pasta', label: 'Pasta' },
  { id: 'sides', label: 'Garlic Bread & Burgers' },
  { id: 'beverages', label: 'Beverages' },
  { id: 'dessert', label: 'Dessert' },
];

export const menuItems = [
  // --- PIZZAS: VEG DOUBLE ---
  {
    id: 1,
    name: 'Onion Tomato Pizza',
    category: 'pizza',
    subCategory: 'Veg Double',
    description: 'A simple classic with fresh onions and juicy tomatoes.',
    price: { regular: 99 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775224852/full-menu/pizzas/farmer-style_awfugn.png',
    badge: 'Veg Double',
  },
  {
    id: 2,
    name: 'Onion Capsicum Pizza',
    category: 'pizza',
    subCategory: 'Veg Double',
    description: 'Crunchy capsicum and fresh onions on a cheesy base.',
    price: { regular: 99 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775224849/full-menu/pizzas/onion-capscicum-pizza_rakoxh.webp',
    badge: 'Veg Double',
  },
  {
    id: 3,
    name: 'Paneer Onion Pizza',
    category: 'pizza',
    subCategory: 'Veg Double',
    description: 'Soft paneer cubes with fresh onions for a light, satisfying bite.',
    price: { regular: 99 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775224910/full-menu/pizzas/Pasted_image_kmwqbo.png',
    badge: 'Veg Double',
  },
  {
    id: 4,
    name: 'Paneer Sweetcorn Pizza',
    category: 'pizza',
    subCategory: 'Veg Double',
    description: 'Tender paneer with sweet golden corn kernels on a cheesy base.',
    price: { regular: 99 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775224850/full-menu/pizzas/paneer-sweetcorn-pizza_zchn3m.avif',
    badge: 'Veg Double',
  },

  // --- PIZZAS: CLASSIC ---
  {
    id: 5,
    name: 'Cheesy Golden Corn Pizza',
    category: 'pizza',
    subCategory: 'Classic',
    description: 'Sweet corn and 100% mozzarella cheese on a classic crust.',
    price: { regular: 179, medium: 299, twoMedium: 399 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775224850/full-menu/pizzas/cheesy-corn-golden-pizza_nsmrh4.jpg',
    badge: 'Classic',
  },
  {
    id: 6,
    name: 'Double Cheese Margherita',
    category: 'pizza',
    subCategory: 'Classic',
    description: 'A classic delight loaded with extra 100% mozzarella cheese.',
    price: { regular: 179, medium: 299, twoMedium: 399 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775224848/full-menu/pizzas/double-cheese-margerita_ppdx9s.jpg',
    badge: 'Classic',
  },

  // --- PIZZAS: DELUXE ---
  {
    id: 7,
    name: 'Paneer Bites Pizza',
    category: 'pizza',
    subCategory: 'Deluxe',
    description: 'Paneer, capsicum, red paprika, and onion on a deluxe crust.',
    price: { regular: 190, medium: 349, twoMedium: 499 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775224848/full-menu/pizzas/double-cheese-margerita_ppdx9s.jpg',
    badge: 'Deluxe',
  },
  {
    id: 8,
    name: 'Classic Veg Pizza',
    category: 'pizza',
    subCategory: 'Deluxe',
    description: 'Capsicum, onion, and tomato — a timeless combination.',
    price: { regular: 190, medium: 349, twoMedium: 499 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775224856/full-menu/pizzas/veg-pizza_fyvpnc.png',
    badge: 'Deluxe',
  },
  {
    id: 9,
    name: 'Veg Treat Pizza',
    category: 'pizza',
    subCategory: 'Deluxe',
    description: 'Jalapeño, capsicum, onion, and tomato for a bold veggie experience.',
    price: { regular: 190, medium: 349, twoMedium: 499 },
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&h=400&fit=https://res.cloudinary.com/nikk25/image/upload/v1775224847/full-menu/pizzas/veg-treat_xczhpn.png',
    badge: 'Deluxe',
  },
  {
    id: 10,
    name: 'Peppy Paneer Pizza',
    category: 'pizza',
    subCategory: 'Deluxe',
    description: 'Paneer, capsicum, and red paprika — a peppery delight.',
    price: { regular: 190, medium: 349, twoMedium: 499 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775224853/full-menu/pizzas/peppy-paneer-pizza_nccwb0.png',
    badge: 'Popular',
  },

  // --- PIZZAS: SUPREME ---
  {
    id: 11,
    name: 'Veggie Paradise Pizza',
    category: 'pizza',
    subCategory: 'Supreme',
    description: 'Golden corn, black olives, capsicum, and red paprika on a supreme base.',
    price: { regular: 219, medium: 399, twoMedium: 549 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775224859/full-menu/pizzas/veg-paradise-pizz_n4xw9r.png',
    badge: 'Supreme',
  },
  {
    id: 12,
    name: 'Tikka Masala Pizza',
    category: 'pizza',
    subCategory: 'Supreme',
    description: 'Tomato, onion, capsicum, and paneer on a rich tandoori sauce base.',
    price: { regular: 219, medium: 399, twoMedium: 549 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775224924/full-menu/pizzas/tikka-masala-pizza_cg9uzx.png',
    badge: 'Supreme',
  },
  {
    id: 13,
    name: 'Farm Fresh Pizza',
    category: 'pizza',
    subCategory: 'Supreme',
    description: 'Tomato, mushroom, onion, and capsicum — farm-fresh flavors on every slice.',
    price: { regular: 219, medium: 399, twoMedium: 549 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775224876/full-menu/pizzas/farmhouse-pizza_c2agtf.png',
    badge: 'Supreme',
  },
  {
    id: 14,
    name: 'Veg Supreme Pizza',
    category: 'pizza',
    subCategory: 'Supreme',
    description: 'Capsicum, paneer, tomato, corn, and cheese — the ultimate veggie supreme.',
    price: { regular: 219, medium: 399, twoMedium: 549 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775224965/full-menu/pizzas/veg-supereme-pizza_s68hwf.png',
    badge: 'Bestseller',
  },

  // --- PIZZAS: DIAMOND ---
  {
    id: 15,
    name: 'Farmer Style Pizza',
    category: 'pizza',
    subCategory: 'Diamond',
    description: 'Onion, tomato, capsicum, corn, and mushroom — rustic and hearty.',
    price: { regular: 249, medium: 499, twoMedium: 649 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775224876/full-menu/pizzas/farmhouse-pizza_c2agtf.png',
    badge: 'Diamond',
  },
  {
    id: 16,
    name: 'Hell Spicy Pizza',
    category: 'pizza',
    subCategory: 'Diamond',
    description: 'Red paprika, jalapeño, capsicum, green chilly, and onion — not for the faint-hearted!',
    price: { regular: 249, medium: 499, twoMedium: 649 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775224853/full-menu/pizzas/peppy-paneer-pizza_nccwb0.png',
    badge: '🔥 Spicy',
  },
  {
    id: 17,
    name: 'Paneer Tikka Twist Pizza',
    category: 'pizza',
    subCategory: 'Diamond',
    description: 'Jalapeño, capsicum, onion, tomato, paneer, and tandoori mayonnaise — a bold fusion.',
    price: { regular: 249, medium: 499, twoMedium: 649 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775224924/full-menu/pizzas/tikka-masala-pizza_cg9uzx.png',
    badge: 'Diamond',
  },
  {
    id: 18,
    name: 'Pizza King',
    category: 'pizza',
    subCategory: 'Diamond',
    description: '9 veggies loaded with cheese & herbs, paneer, jalapeño, black olives, tomato, onion, capsicum, red paprika, and mushroom.',
    price: { regular: 249, medium: 499, twoMedium: 649 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775224859/full-menu/pizzas/veg-paradise-pizz_n4xw9r.png',
    badge: '👑 King',
  },

  // --- PASTA ---
  {
    id: 19,
    name: 'Red Sauce Pasta',
    category: 'pasta',
    description: 'A classic Italian delight with a tangy, herby tomato-based sauce.',
    price: { regular: 189 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775225016/full-menu/pasta/red-sauce-pasta_rxs99l.png',
    badge: 'Classic',
  },
  {
    id: 20,
    name: 'Creamy White Sauce Pasta',
    category: 'pasta',
    description: 'Indulgently creamy and smooth, made with rich, cheesy Béchamel sauce.',
    price: { regular: 199 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775225018/full-menu/pasta/white-sauce-pasta_zjjszx.png',
    badge: 'Favorite',
  },
  {
    id: 21,
    name: 'Mixed Sauce Pasta',
    category: 'pasta',
    description: 'The best of both worlds: a perfect blend of creamy white and tangy red sauces.',
    price: { regular: 210 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775225028/full-menu/pasta/mixed-sauce-pasta_chvnqd.png',
    badge: 'Bestseller',
  },
  {
    id: 22,
    name: 'Tandoori Paneer Pasta',
    category: 'pasta',
    description: 'A bold fusion twist featuring smoky tandoori flavors with soft paneer.',
    price: { regular: 220 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775225027/full-menu/pasta/tandoori-paneer-pasta_wyam2n.png',
    badge: 'Fusion',
  },
  {
    id: 23,
    name: 'Bake Any Pasta (Add-on)',
    category: 'pasta',
    description: 'Upgrade any pasta to a baked version with a golden cheesy crust on top.',
    price: { regular: 50 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775225019/full-menu/pasta/paneer-baked-pasta_ybxmjg.png',
    badge: 'Add-on',
  },

  // --- GARLIC BREAD & BURGERS ---
  {
    id: 24,
    name: 'Garlic Breadsticks',
    category: 'sides',
    subCategory: 'Garlic Bread',
    description: 'Golden-brown, crispy breadsticks infused with rich garlic butter and aromatic herbs.',
    price: { regular: 80 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775225285/full-menu/garlicbread/breadsticks_ptzaki.png',
    badge: 'Classic',
  },
  {
    id: 25,
    name: 'Stuffed Garlic Breadstick',
    category: 'sides',
    subCategory: 'Garlic Bread',
    description: 'Freshly baked and stuffed with sweet corn, jalapeños, and gooey melted cheese.',
    price: { regular: 140 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775225297/full-menu/garlicbread/stuffed-garlic-breadsticks_xcezrd.png',
    badge: 'Premium',
  },
  {
    id: 26,
    name: 'Cheesy Garlic Breadstick',
    category: 'sides',
    subCategory: 'Garlic Bread',
    description: 'Classic garlic bread loaded with 100% melted mozzarella cheese.',
    price: { regular: 150 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775225297/full-menu/garlicbread/cheesy-garlic-breadsticks_ziebk5.png',
    badge: 'Popular',
  },
  {
    id: 27,
    name: 'Veggie Burger',
    category: 'sides',
    subCategory: 'Burger',
    description: 'A fresh and crispy veggie patty burger with classic toppings.',
    price: { regular: 60 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775225293/full-menu/garlicbread/veggie-burger_e34gyk.png',
    badge: 'Classic',
  },
  {
    id: 28,
    name: 'Tandoori Burger',
    category: 'sides',
    subCategory: 'Burger',
    description: 'A smoky, spiced tandoori patty burger with mint chutney and fresh veggies.',
    price: { regular: 90 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775225285/full-menu/garlicbread/tandoori-burger_wkpygq.png',
    badge: 'Popular',
  },
  {
    id: 29,
    name: 'Cheese Burger',
    category: 'sides',
    subCategory: 'Burger',
    description: 'A juicy patty loaded with melted cheese, fresh lettuce, and special sauce.',
    price: { regular: 110 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775225293/full-menu/garlicbread/cheesy-veg-burger_fkvdka.png',
    badge: 'Cheesy',
  },

  // --- BEVERAGES: MILK SHAKES ---
  {
    id: 30,
    name: 'Vanilla Beans Shake',
    category: 'beverages',
    subCategory: 'Milk Shake',
    description: 'A rich and creamy vanilla milkshake made with real vanilla beans.',
    price: { regular: 100 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775225045/full-menu/shakes/vanilla-beans-shake_irn8nj.png',
    badge: 'Classic',
  },
  {
    id: 31,
    name: 'Butter Scotch Shake',
    category: 'beverages',
    subCategory: 'Milk Shake',
    description: 'Smooth and indulgent butterscotch milkshake with a caramel finish.',
    price: { regular: 100 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775225066/full-menu/shakes/butter-scotch-shake_bqnnyb.png',
    badge: 'Sweet',
  },
  {
    id: 32,
    name: 'Strawberry Shake',
    category: 'beverages',
    subCategory: 'Milk Shake',
    description: 'Fresh and fruity strawberry milkshake, thick and refreshing.',
    price: { regular: 100 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775225094/full-menu/shakes/strawberyy-shake_itadsa.png',
    badge: 'Fresh',
  },
  {
    id: 33,
    name: 'Chocolate Shake',
    category: 'beverages',
    subCategory: 'Milk Shake',
    description: 'A decadent thick chocolate milkshake for all the choco lovers.',
    price: { regular: 110 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775225065/full-menu/shakes/choclate-sahke_eslyqs.png',
    badge: 'Popular',
  },
  {
    id: 34,
    name: 'Oreo Shake',
    category: 'beverages',
    subCategory: 'Milk Shake',
    description: 'Crushed Oreo cookies blended into a luscious creamy milkshake.',
    price: { regular: 120 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775225113/full-menu/shakes/oero-shake_ytca9g.png',
    badge: 'Bestseller',
  },
  {
    id: 35,
    name: 'Oreo Strawberry Shake',
    category: 'beverages',
    subCategory: 'Milk Shake',
    description: 'The perfect combo of Oreo crunch and fresh strawberry in one thick shake.',
    price: { regular: 130 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775225047/full-menu/shakes/oreo-strawberry-shake_myrl0z.png',
    badge: 'Special',
  },

  // --- BEVERAGES: COFFEE ---
  {
    id: 36,
    name: 'Hot Coffee',
    category: 'beverages',
    subCategory: 'Coffee',
    description: 'A warm, comforting cup of freshly brewed hot coffee.',
    price: { regular: 70 },
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=600&h=400&fit=crophttps://res.cloudinary.com/nikk25/image/upload/v1775225048/full-menu/shakes/hot-coffee_nyke96.png',
    badge: 'Classic',
  },
  {
    id: 37,
    name: 'Cold Coffee',
    category: 'beverages',
    subCategory: 'Coffee',
    description: 'A smooth, chilled blend of premium coffee and creamy milk.',
    price: { regular: 80 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775225177/full-menu/shakes/cold-coffee_kyetgj.png',
    badge: 'Favorite',
  },
  {
    id: 38,
    name: 'Caramel Cold Coffee',
    category: 'beverages',
    subCategory: 'Coffee',
    description: 'Chilled cold coffee with a rich drizzle of sweet caramel sauce.',
    price: { regular: 90 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775225044/full-menu/shakes/caramel-cold-coffee_bvcvlo.png',
    badge: 'Sweet',
  },
  {
    id: 39,
    name: 'Chocolate Crunch Coffee',
    category: 'beverages',
    subCategory: 'Coffee',
    description: 'Cold coffee topped with chocolate crunch for a satisfying bite with every sip.',
    price: { regular: 100 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775225044/full-menu/shakes/crunch-coffee_e3gbbx.png',
    badge: 'Indulgent',
  },

  // --- BEVERAGES: MOJITO ---
  {
    id: 40,
    name: 'Masala Lemonade',
    category: 'beverages',
    subCategory: 'Mojito',
    description: 'A tangy Indian-style spiced lemonade — refreshing with a kick of masala.',
    price: { regular: 80 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775225249/full-menu/shakes/masala-lemonade_xvllyp.png',
    badge: 'Desi',
  },
  {
    id: 41,
    name: 'Virgin Mojito',
    category: 'beverages',
    subCategory: 'Mojito',
    description: 'Classic mint and lime mojito, muddled fresh and served chilled.',
    price: { regular: 100 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775231167/full-menu/shakes/virgin_mojito.png',
    badge: 'Classic',
  },
  {
    id: 42,
    name: 'Cool Blue Mojito',
    category: 'beverages',
    subCategory: 'Mojito',
    description: 'A vibrant blue lagoon mojito — visually stunning and refreshingly cool.',
    price: { regular: 100 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775225076/full-menu/shakes/cool-blue-mojito_qrkq6u.png',
    badge: 'Refreshing',
  },
  {
    id: 43,
    name: 'Watermelon Mojito',
    category: 'beverages',
    subCategory: 'Mojito',
    description: 'Juicy watermelon blended into a minty mojito — summer in a glass.',
    price: { regular: 120 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775225196/full-menu/shakes/watermelon-mojito_qjniya.png',
    badge: 'Seasonal',
  },
  {
    id: 44,
    name: 'Green Apple Mojito',
    category: 'beverages',
    subCategory: 'Mojito',
    description: 'Crisp green apple with fresh mint and lime — tangy and refreshing.',
    price: { regular: 110 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775225048/full-menu/shakes/green-apple-mojito_z3roxm.png',
    badge: 'Tangy',
  },

  // --- DESSERT ---
  {
    id: 45,
    name: 'Chocolava',
    category: 'dessert',
    description: 'A warm, gooey chocolate lava cake with a molten center — pure indulgence.',
    price: { regular: 79 },
    image: 'https://res.cloudinary.com/nikk25/image/upload/v1775225697/full-menu/chocolava-cake.png',
    badge: '🍫 Must Try', 
  },
];